# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-04 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_name', models.CharField(max_length=50, verbose_name='Build Name')),
                ('isinternal', models.BooleanField()),
                ('standard_push', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Codeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeline_name', models.CharField(max_length=50, verbose_name='Name')),
                ('parent_codeline', models.CharField(max_length=50, verbose_name='Parent')),
                ('tag', models.CharField(max_length=50, verbose_name='Tag')),
                ('bug_id', models.CharField(max_length=50, verbose_name='Bug Id')),
                ('do_push', models.BooleanField()),
                ('build_setup', models.CharField(max_length=50, verbose_name='Wrapper Build Setup')),
                ('sanity_setup', models.BooleanField()),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
            ],
        ),
        migrations.AddField(
            model_name='buildlist',
            name='codeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='initial.Codeline'),
        ),
    ]
