# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-05 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildlist',
            name='isinternal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buildlist',
            name='standard_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codeline',
            name='do_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codeline',
            name='sanity_setup',
            field=models.BooleanField(default=False),
        ),
    ]
